name: Tests
on: push

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:

    - name: Copy Repo Files
      uses: actions/checkout@master

    - name: Publish Docker Image to GPR
      uses: dhainzl/gpr-docker-publish@dhainzl/build-args
      with:
        IMAGE_NAME: 'test-docker-action-v2'
        TAG: 'my-optional-tag-name'
        DOCKERFILE_PATH: 'Dockerfile'
        BUILD_CONTEXT: '.'
        BUILD_PARAMS: "--build-arg foo=bar --build-arg 'msg=hello world'"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
